fos_user:
  db_driver: orm # other valid values are 'mongodb' and 'couchdb'
  firewall_name: main
  user_class: App\Entity\User
  from_email:
    address: "random.random@hotmail.com"
    sender_name: "random"
  registration:
          form:
              type: App\Form\RegistrationType